service: item-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    ITEMS_TABLE_NAME: ${self:custom.ItemsTable.name}
  iamRoleStatements:
    - ${file(iam/ItemsTableIAM.yml):ItemsTableIAM} 

resources:
  Resources:
    ItemsTable: ${file(resources/ItemsTable.yml):ItemsTable}

functions:
  createItem:
    handler: src/handlers/createItem.handler
    events:
      - http:
          method: POST
          path: /item

  getItems:
    handler: src/handlers/getItems.handler
    events:
      - http:
          method: GET
          path: /items

  getTodo:
    handler: src/handlers/getItem.handler
    events:
      - http:
          method: GET
          path: /item/{id}

custom:
  ItemsTable:
    name: !Ref ItemsTable
    arn: !GetAtt ItemsTable.Arn
  bundle:
    linting: false